networks:
    employee_testing:
        external: true

services:

    service:
        image: sebn-employee-testing
        env_file: ./.env
        networks:
            - employee_testing

version: "3.8"
